//
//  Users.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Users: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _employeeID: NSNumber?
    var _employees: [String]?
    var _isManager: NSNumber?
    var _manager: NSNumber?
    var _name: String?
    var _password: String?
    var _streak: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "hackgsu-mobilehub-1785929666-users"
    }
    
    class func hashKeyAttribute() -> String {

        return "_employeeID"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_employeeID" : "employeeID",
               "_employees" : "employees",
               "_isManager" : "isManager",
               "_manager" : "manager",
               "_name" : "name",
               "_password" : "password",
               "_streak" : "streak",
        ]
    }
}
